# Generated by Django 3.1.3 on 2020-11-05 04:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tile',
            fields=[
                ('tileID', models.AutoField(primary_key=True, serialize=False)),
                ('lunchDate', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('status', models.CharField(choices=[('live', 'live'), ('pending', 'pending by someone'), ('archived', 'Archived - not available anymore')], default='live', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='task',
            fields=[
                ('taskID', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('orderField', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('tileType', models.CharField(choices=[('survey', 'survey - survey description'), ('discussion', 'discussion - discussion description'), ('diary', 'diary - diary description')], default='survey', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tileID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tileTask.tile')),
            ],
        ),
    ]
